### PR TITLE
Include ClientAddr in Packet

### PR DESCRIPTION
**Pull request by thomseddon**
I needed access to the actual client source IP, happy to change the implementation if there's a preferred method

### CODE REVIEW

**Comment by bronze1man** [comment]
Sorry, this pull request is not good to me.
I think it is ok to add a string type ClientAddr field in the packet struct. 
It is not ok to add a net.Addr type into packet struct. It is difficult to add a net.Addr type into the packet struct for test.
And It is difficult to json marshal or unmarshal the packet struct after you add the net.Addr type.

**Comment by thomseddon** [comment]
No problem, I only access the string anyway so could make this:

```
type Packet struct {
	Secret        string
	Code          PacketCode
	Identifier    uint8
	Authenticator [16]byte
	AVPs          []AVP
        ClientAddr    string
}
```

?

**Comment by bronze1man** [comment]
Yes, this struct looks good to me.
By the way, please do not change parameter number of DecodePacket as it is public function, just set that field after the call of DecodePacket.
Change parameters of public function may cause other's program not work. I call it bc (break compatibility).

**Comment by thomseddon** [comment]
Very good point! The original commit was actually from 2017 as quick fix, I have been updating our project that used it so thought I should pass it back :)

I have also updated the travis config, it seems the "release" tag is now unknown - let me know what go versions you would like to support (https://github.com/bronze1man/radius/pull/19/commits/c6f427208f3e4e640d2328120fe406cfe3a386e5)

**Comment by bronze1man** [comment]
go 1.9-1.12 looks good to me.

**Pull request merged**
